name: Benchmark
on:
  workflow_call:
    inputs:
      toolchain:
        description: Rust toolchain
        required: true
        type: string

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: Keep this updated
        target:
          - x86_64-unknown-none
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.target }} target
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
          target: ${{ matrix.target }}
          cache-workspaces: ./charlotte_core
      - name: Run Benchmarks
        run: cargo bench
        working-directory: ./charlotte_core